package home;
// Generated Sep 3, 2014 1:26:11 PM by Hibernate Tools 3.2.1.GA



/**
 * Messages generated by hbm2java
 */
public class Messages  implements java.io.Serializable {


     private Integer id;
     private Houses houses;
     private User user;
     private String message;

    public Messages() {
    }

    public Messages(Houses houses, User user, String message) {
       this.houses = houses;
       this.user = user;
       this.message = message;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Houses getHouses() {
        return this.houses;
    }
    
    public void setHouses(Houses houses) {
        this.houses = houses;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}


