package home;
// Generated Sep 3, 2014 1:26:11 PM by Hibernate Tools 3.2.1.GA



/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private RoleId id;
     private User user;

    public Role() {
    }

    public Role(RoleId id, User user) {
       this.id = id;
       this.user = user;
    }
   
    public RoleId getId() {
        return this.id;
    }
    
    public void setId(RoleId id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


