package home;
// Generated Sep 3, 2014 1:26:11 PM by Hibernate Tools 3.2.1.GA



/**
 * Photos generated by hbm2java
 */
public class Photos  implements java.io.Serializable {


     private Integer id;
     private Houses houses;
     private String photos;

    public Photos() {
    }

    public Photos(Houses houses, String photos) {
       this.houses = houses;
       this.photos = photos;
    }
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Houses getHouses() {
        return this.houses;
    }
    
    public void setHouses(Houses houses) {
        this.houses = houses;
    }
    public String getPhotos() {
        return this.photos;
    }
    
    public void setPhotos(String photos) {
        this.photos = photos;
    }




}


