package home;
// Generated Sep 3, 2014 1:26:11 PM by Hibernate Tools 3.2.1.GA



/**
 * RoleId generated by hbm2java
 */
public class RoleId  implements java.io.Serializable {


     private String userUsername;
     private String role;

    public RoleId() {
    }

    public RoleId(String userUsername, String role) {
       this.userUsername = userUsername;
       this.role = role;
    }
   
    public String getUserUsername() {
        return this.userUsername;
    }
    
    public void setUserUsername(String userUsername) {
        this.userUsername = userUsername;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RoleId) ) return false;
		 RoleId castOther = ( RoleId ) other; 
         
		 return ( (this.getUserUsername()==castOther.getUserUsername()) || ( this.getUserUsername()!=null && castOther.getUserUsername()!=null && this.getUserUsername().equals(castOther.getUserUsername()) ) )
 && ( (this.getRole()==castOther.getRole()) || ( this.getRole()!=null && castOther.getRole()!=null && this.getRole().equals(castOther.getRole()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserUsername() == null ? 0 : this.getUserUsername().hashCode() );
         result = 37 * result + ( getRole() == null ? 0 : this.getRole().hashCode() );
         return result;
   }   


}


