package home;
// Generated Sep 3, 2014 1:26:11 PM by Hibernate Tools 3.2.1.GA



/**
 * SellRentId generated by hbm2java
 */
public class SellRentId  implements java.io.Serializable {


     private String type;
     private String housesOdos;

    public SellRentId() {
    }

    public SellRentId(String type, String housesOdos) {
       this.type = type;
       this.housesOdos = housesOdos;
    }
   
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getHousesOdos() {
        return this.housesOdos;
    }
    
    public void setHousesOdos(String housesOdos) {
        this.housesOdos = housesOdos;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SellRentId) ) return false;
		 SellRentId castOther = ( SellRentId ) other; 
         
		 return ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
 && ( (this.getHousesOdos()==castOther.getHousesOdos()) || ( this.getHousesOdos()!=null && castOther.getHousesOdos()!=null && this.getHousesOdos().equals(castOther.getHousesOdos()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         result = 37 * result + ( getHousesOdos() == null ? 0 : this.getHousesOdos().hashCode() );
         return result;
   }   


}


