package home;
// Generated Sep 3, 2014 1:26:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String username;
     private String password;
     private String name;
     private String surname;
     private String email;
     private String number;
     private boolean pending;
     private Set<Houses> houseses = new HashSet<Houses>(0);
     private Set<Role> roles = new HashSet<Role>(0);
     private Set<Messages> messageses = new HashSet<Messages>(0);

    public User() {
    }

    public User(String username,String password)
    {
      this.username=username;
      this.password=password;    
    } 
	
    public User(String username, String password, String name, String surname, String email, String number, boolean pending) {
        this.username = username;
        this.password = password;
        this.name = name;
        this.surname = surname;
        this.email = email;
        this.number = number;
        this.pending = pending;
    }
    public User(String username, String password, String name, String surname, String email, String number, boolean pending, Set<Houses> houseses, Set<Role> roles, Set<Messages> messageses) {
       this.username = username;
       this.password = password;
       this.name = name;
       this.surname = surname;
       this.email = email;
       this.number = number;
       this.pending = pending;
       this.houseses = houseses;
       this.roles = roles;
       this.messageses = messageses;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public boolean isPending() {
        return this.pending;
    }
    
    public void setPending(boolean pending) {
        this.pending = pending;
    }
    public Set<Houses> getHouseses() {
        return this.houseses;
    }
    
    public void setHouseses(Set<Houses> houseses) {
        this.houseses = houseses;
    }
    public Set<Role> getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }
    public Set<Messages> getMessageses() {
        return this.messageses;
    }
    
    public void setMessageses(Set<Messages> messageses) {
        this.messageses = messageses;
    }




}


